spring:
  application:
    name: DishPatch

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/dishpatch}
    username: ${MYSQL_USERNAME:testuser}
    password: ${MYSQL_PASSWORD:testpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: ${JWT_SECRET:default-secret}